name: test
on:
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Install Dependencies
        run: npm ci
        timeout-minute: 10
      - name: Run all tests
        run: npm run test
